name = "maven"
main = "src/index.ts"
compatibility_date = "2023-04-22"
usage_model = "bundled"
workers_dev = false

[[kv_namespaces]]
binding = "MAVEN_KV"
id = "130b4e2d0b1c43ae832f4139f105cd05"
preview_id = "8125913e46484230b4ec54915b7c0fed"

[[queues.producers]]
queue = "maven-to-index"
binding = "MAVEN_QUEUE"

[[queues.consumers]]
queue = "maven-to-index"
max_batch_size = 100
max_batch_timeout = 30

[vars]
B2_ENDPOINT = "https://s3.eu-central-003.backblazeb2.com"
B2_REGION = "eu-central-003"
B2_BUCKET = "maven-quiltmc-org"
B2_KEY = "003fac8dd2ef1560000000004"
CLOUDFLARE_ZONE = "70e277f4d6fd3fa77f7490194ca238f8"
ORIGIN = "https://maven.quiltmc-testing.xyz/"
PREFIX = "/publish/"
ALLOWED_REPOS = "[\"snapshot\",\"release\"]"
